### ISSUE TITLE
Multiline strings on comments are still highlighted

### ISSUE THREAD

**Issue by Oples** [Oples/nanorc-nim#1]
![image](https://user-images.githubusercontent.com/21972291/118397024-6d2a6300-b652-11eb-912b-a958726f9491.png)
![image](https://user-images.githubusercontent.com/21972291/118397212-43257080-b653-11eb-9ab7-ae90e013d9d2.png)

Multiline strings are broken

**Comment by eggplants** [comment]
related?
![image](https://user-images.githubusercontent.com/42153744/176998351-b878b609-7496-490a-8062-a5c0dd7dedaf.png)

https://learnxinyminutes.com/docs/nim/

**Comment by Oples** [comment]
Sadly no, that deserves it's own issue but this is small repo so I might as well fix both while I'm here.

Thank you for sharing the info!

**Comment by Oples** [comment]
Oops wrong button
